// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "EEz",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "EEz",
            targets: ["AppModule"],
            bundleIdentifier: "name.Riboldi.EEz",
            teamIdentifier: "8FQWGFFDQM",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .finance
        )
    ],
    dependencies: [
        .package(url: "https://github.com/yaslab/CSV.swift.git", "2.5.2"..<"3.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "CSV", package: "csv.swift")
            ],
            path: "."
        )
    ],
    swiftLanguageVersions: [.version("6")]
)